### ISSUE TITLE
两面板中间有间隔

### ISSUE THREAD

**Issue by lingr7** [wuxiaofei01/Light-bf#3]
<img width="578" alt="空隙" src="https://user-images.githubusercontent.com/37898999/187164586-c64b0da5-f26a-4b2c-b597-bf956024ceb8.png">
这两个地方都有间隔。思源最新版本2.1.10

**Comment by wxf-0415** [comment]
你好，请问有具体截图么?能详细描述一下么?



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月29日(周一) 下午4:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wxf-0415/Light-bf] 两面板中间有间隔 (Issue #3)

**Comment by wxf-0415** [comment]
你好，这个问题我发现没办法解决。同样，在其他作者的主题中，也普遍存在这一点，这是由于Siyuan框架的设计ui导致。没办法通过主题进行调整。
给出建议：将文档树背景色调整为白色，这样在视觉上会发现没有间隔。

**Comment by lingr7** [comment]
好的，另外发现<img width="644" alt="代码块样式有问题" src="https://user-images.githubusercontent.com/37898999/187170765-ab02e7d3-38b1-4da2-b634-7938d7fe1977.png">
代码块最后一行显示异常。

**Comment by lingr7** [comment]
> 



> 

那这个有无向siyuan的仓库提过issue，如果没有，如你有空，可以去提一下，如没空我去提一下。

**Comment by wxf-0415** [comment]
> > 
> 
> > 
> 
> 那这个有无向siyuan的仓库提过issue，如果没有，如你有空，可以去提一下，如没空我去提一下。

这个问题，应该是没有issue的，麻烦你提一下了。我再把代码块给改改。（但是，也有可能是我不会改，导致有分界线，也是有可能的）

**Comment by wuxiaofei01** [comment]
> > 
> 
> > 
> 
> 那这个有无向siyuan的仓库提过issue，如果没有，如你有空，可以去提一下，如没空我去提一下。

已经修复，等待merge就好了。

**Comment by lingr7** [comment]
好的，就是说代码块高亮的修复了。面板那边我去提一下issue.

**Comment by lingr7** [comment]
https://github.com/siyuan-note/siyuan/issues/5752
这个我提出给siyuan了，Issue被很快关闭了。我找了一下集市，除了官方明亮主题外，还有一个主题也是异色，但是无间隔，[BluePrint From Tsundoku](https://github.com/YYHCOPPOLO/BluePrint-From-Tsundoku)
应该能通过配置主题来实现
<img width="835" alt="异色无间隔" src="https://user-images.githubusercontent.com/37898999/187362580-741c4e6b-af87-447d-8093-384c993cd7c6.png">

**Comment by wuxiaofei01** [comment]
好的，我后续会尝试修复一下，预期是在周四之前吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月30日(周二) 下午2:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [wxf-0415/Light-bf] 两面板中间有间隔 (Issue #3)




 
siyuan-note/siyuan#5752
 这个我提出给siyuan了，Issue被很快关闭了。我找了一下集市，除了官方明亮主题外，还有一个主题也是异色，但是无间隔，BluePrint From Tsundoku
 应该能通过配置主题来实现

**Comment by lingr7** [comment]
收到。感谢及时的回复。

**Comment by wuxiaofei01** [comment]
> [siyuan-note/siyuan#5752](https://github.com/siyuan-note/siyuan/issues/5752) 这个我提出给siyuan了，Issue被很快关闭了。我找了一下集市，除了官方明亮主题外，还有一个主题也是异色，但是无间隔，[BluePrint From Tsundoku](https://github.com/YYHCOPPOLO/BluePrint-From-Tsundoku) 应该能通过配置主题来实现 <img alt="异色无间隔" width="835" src="https://user-images.githubusercontent.com/37898999/187362580-741c4e6b-af87-447d-8093-384c993cd7c6.png">

这个问题，我暂时没法解决。还得考研呢。。所以，抱歉了。。（尝试找了一下bug，但是没找到解决方案）

**Comment by lingr7** [comment]
> > [siyuan-note/siyuan#5752](https://github.com/siyuan-note/siyuan/issues/5752) 这个我提出给siyuan了，Issue被很快关闭了。我找了一下集市，除了官方明亮主题外，还有一个主题也是异色，但是无间隔，[BluePrint From Tsundoku](https://github.com/YYHCOPPOLO/BluePrint-From-Tsundoku) 应该能通过配置主题来实现 <img alt="异色无间隔" width="835" src="https://user-images.githubusercontent.com/37898999/187362580-741c4e6b-af87-447d-8093-384c993cd7c6.png">
> 
> 这个问题，我暂时没法解决。还得考研呢。。所以，抱歉了。。（尝试找了一下bug，但是没找到解决方案）

理解
